DanielBui64/rails-airbnb-clone

- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20220221221908_devise_create_users.rb
- db/schema.rb
- test/models/user_test.rb
> Added devise

- app/models/boat.rb
- app/models/booking.rb
- app/models/user.rb
- db/migrate/20220222163924_create_boats.rb
- db/migrate/20220222164006_create_bookings.rb
- db/migrate/20220222164222_add_fields_to_user.rb
- db/schema.rb
- test/models/boat_test.rb
- test/models/booking_test.rb
> Created all models with their validations & assocciations.

- Gemfile
- Gemfile.lock
- app/models/boat.rb
- app/models/user.rb
- db/seeds.rb
Please accept so we could go eat our lunch
> Added seeds with minor changes to user(owner) and boat(type).

- config/routes.rb
> Added all routes.

- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
theses are the pictures for the homepage
> pictures in homepage

- app/controllers/boats_controller.rb
- app/views/boats/index.html.erb
> Created boats page with cards.

- app/controllers/dashboard_controller.rb
- app/views/dashboard/my_boats.html.erb
> Created my_boats and linked it to dashboard controller.

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/dashboard/my_boats.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
please review my code for the footer.
> creating the footer

- app/assets/stylesheets/components/_footer.scss
- app/views/shared/_footer.html.erb
Please check if the footer works
> Fixed the footer

- app/views/boats/show.html.erb
> Created show page for boat.

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/_banner.html.erb
- app/views/pages/home.html.erb
Please try and see if the homepage is working
> homepage_styling

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_my_boats.scss
- app/controllers/boats_controller.rb
- app/models/boat.rb
- app/views/boats/new.html.erb
- app/views/dashboard/index.html.erb
- app/views/dashboard/my_boats.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20220223191712_create_active_storage_tables.active_storage.rb
- db/schema.rb
> Add dotenv and integrated cloudinary

- app/assets/stylesheets/components/_footer.scss
Please check if this is what you meant for the footer
> the footer is now transparent

- app/controllers/dashboard_controller.rb
- app/views/dashboard/index.html.erb
> Created the dashboard page.

- app/controllers/bookings_controller.rb
- app/views/bookings/confirm.html.erb
> Created the booking confirm page.

- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/dashboard/index.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/shared/_navbar.html.erb
- config/initializers/devise.rb
> Added option to update user profilr picture.

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/controllers/boats_controller.rb
- app/javascript/controllers/mapbox_controller.js
- app/views/boats/index.html.erb
- db/seeds.rb
- package.json
- yarn.lock
> Displaying map

- app/controllers/boats_controller.rb
- app/views/boats/edit.html.erb
- app/views/dashboard/my_boats.html.erb
> Added update page for boats.

- app/assets/stylesheets/pages/_index.scss
- app/controllers/boats_controller.rb
- app/models/boat.rb
- app/views/boats/index.html.erb
- app/views/boats/new.html.erb
- app/views/boats/show.html.erb
- app/views/dashboard/index.html.erb
- app/views/dashboard/my_boats.html.erb
- config/environments/production.rb
Added Cloudinary multi-image access so hopefully it works on Heroku!! Review and let's test it :)
> added photos to browsing page and boat details page

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
> wrapped footer in div and added margin

- app/controllers/bookings_controller.rb
- app/views/dashboard/my_bookings.html.erb
- config/routes.rb
> Implemented the accept function with some layout modifications.

- app/views/boats/index.html.erb
- app/views/dashboard/my_boats.html.erb
- app/views/pages/_banner.html.erb
Cards: Reduced number of characters displayed on cards on index & my_boats; Homepage: button color change
> Small changes on cards & homepage

- app/assets/stylesheets/components/_map.scss
- app/views/boats/index.html.erb
> fixed map to the top right side

- app/controllers/boats_controller.rb
- app/views/boats/show.html.erb
> added owner's avatar to booking form

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Feel free to change the innerText if you wanna..
> added cards to replace the carousel

- app/assets/stylesheets/components/_banner.scss
- app/views/shared/_navbar.html.erb
> fixed home icon and banner size

- app/views/boats/edit.html.erb
- app/views/boats/show.html.erb
- app/views/bookings/confirm.html.erb
Changed Edit button to say Confirm Edit
Added Pop-up to confirm booking
> changed wording and add pop-up to confirmation

- db/seeds.rb
> Minor seed changes

- app/assets/stylesheets/components/_map.scss
- app/views/boats/_info_window.html.erb
> fixed the font for the popup map
